import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfigFromFile } from "vite";
import type { Plugin, UserConfig } from "vite";
import { resolveServePort } from "../shared/servePort";
import {
  REPORT_URL_PATH,
} from "../shared/paths";
import {
  collectScanModuleRelPaths,
  embedGlobKeyFromRelPath,
} from "./collectScanModules";
import {
  flattenViteAlias,
  INERTIA_SHIM_IDS,
  resolveWithConsumerAliases,
  ZIGGY_SHIM_ID,
  type FlatAlias,
} from "./consumerAlias";

export const VIRTUAL_PLAYGROUND_MODULES_ID = "virtual:dslinter/playground-modules";
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_PLAYGROUND_MODULES_ID}`;

const pluginDir = dirname(fileURLToPath(import.meta.url));
const inertiaShimPath = resolve(pluginDir, "shims/inertia-react.tsx");
const ziggyShimPath = resolve(pluginDir, "shims/ziggy-js.ts");

export type DslinterVitePluginOptions = {
  /** Scan root (repo root passed to `npx dslinter`). Defaults to `DSLINTER_SCAN_ROOT` or `process.cwd()`. */
  scanRoot?: string;
  /** Host Vite project root for `@/` aliases (Laravel/Inertia). */
  consumerViteRoot?: string;
  /** Scanner HTTP port for report + SSE proxy in `serve` mode. */
  servePort?: number;
};

function generatePlaygroundModulesSource(
  scanRoot: string,
  relPaths: string[],
): string {
  const root = resolve(scanRoot);
  const lines: string[] = [
    "// Generated by dslinter/vite — do not edit",
  ];

  for (let i = 0; i < relPaths.length; i++) {
    const rel = relPaths[i]!;
    const abs = resolve(root, rel).replace(/\\/g, "/");
    lines.push(`import * as __dslinter_m${i} from ${JSON.stringify(abs)};`);
  }

  lines.push("export const scanPlaygroundModules = {");
  for (let i = 0; i < relPaths.length; i++) {
    const key = embedGlobKeyFromRelPath(relPaths[i]!);
    lines.push(`  ${JSON.stringify(key)}: __dslinter_m${i},`);
  }
  lines.push("};");

  return lines.join("\n");
}

/**
 * Vite plugin: virtual playground module map, scanner proxy, react dedupe, fs.allow for scan root.
 *
 * @example
 * ```ts
 * import dslinter from "dslinter/vite";
 * export default defineConfig({ plugins: [dslinter()] });
 * ```
 */
export default function dslinter(
  options: DslinterVitePluginOptions = {},
): Plugin {
  const scanRoot = resolve(
    options.scanRoot ??
      process.env.DSLINTER_SCAN_ROOT ??
      process.cwd(),
  );
  const consumerViteRoot = resolve(
    options.consumerViteRoot ??
      process.env.DSLINTER_CONSUMER_VITE_ROOT ??
      "",
  );
  const servePort = options.servePort ?? resolveServePort();
  let relPaths: string[] = [];
  let consumerAliases: FlatAlias[] = [];

  return {
    name: "dslinter",
    enforce: "pre",

    config(config, { mode }): UserConfig {
      const proxy =
        mode === "serve"
          ? {
              [REPORT_URL_PATH]: {
                target: `http://127.0.0.1:${servePort}`,
                changeOrigin: true,
              },
              "/events": {
                target: `http://127.0.0.1:${servePort}`,
                changeOrigin: true,
              },
            }
          : undefined;

      const allowRoots = [scanRoot];
      if (consumerViteRoot && existsSync(consumerViteRoot)) {
        allowRoots.push(consumerViteRoot);
      }
      const existingAllow = config.server?.fs?.allow;
      const fsAllow = Array.isArray(existingAllow)
        ? [...existingAllow, ...allowRoots]
        : allowRoots;

      return {
        resolve: {
          dedupe: ["react", "react-dom"],
        },
        optimizeDeps: {
          exclude: ["dslinter"],
        },
        server: {
          fs: {
            allow: fsAllow,
          },
          proxy,
        },
      };
    },

    async configResolved(config) {
      relPaths = collectScanModuleRelPaths(scanRoot);
      consumerAliases = [];
      const root =
        consumerViteRoot && existsSync(consumerViteRoot)
          ? consumerViteRoot
          : null;
      if (!root) return;
      try {
        const loaded = await loadConfigFromFile(
          { command: config.command, mode: config.mode },
          undefined,
          root,
        );
        consumerAliases = flattenViteAlias(
          loaded?.config?.resolve?.alias,
          root,
        );
      } catch {
        consumerAliases = [];
      }
    },

    resolveId(id, importer) {
      if (id === VIRTUAL_PLAYGROUND_MODULES_ID) {
        return RESOLVED_VIRTUAL_ID;
      }

      if (!importer || !isPlaygroundModuleImporter(importer, scanRoot, relPaths)) {
        return null;
      }

      if (INERTIA_SHIM_IDS.has(id) || id.startsWith("@inertiajs/react/")) {
        return inertiaShimPath;
      }
      if (id === ZIGGY_SHIM_ID || id === "ziggy") {
        return ziggyShimPath;
      }

      if (consumerAliases.length > 0) {
        const resolved = resolveWithConsumerAliases(id, consumerAliases);
        if (resolved) return resolved;
      }

      return null;
    },

    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return;
      return generatePlaygroundModulesSource(scanRoot, relPaths);
    },

    configureServer(server) {
      const refresh = () => {
        relPaths = collectScanModuleRelPaths(scanRoot);
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
        if (mod) server.moduleGraph.invalidateModule(mod);
      };
      server.watcher.add(scanRoot);
      server.watcher.on("add", refresh);
      server.watcher.on("unlink", refresh);
    },
  };
}

export { collectScanModuleRelPaths, embedGlobKeyFromRelPath };

/** True when `importer` is a scanned playground module (per `include_dirs` / walk). */
function isPlaygroundModuleImporter(
  importer: string,
  scanRoot: string,
  relPaths: string[],
): boolean {
  const norm = importer.replace(/\\/g, "/");
  const root = resolve(scanRoot).replace(/\\/g, "/");
  const rootPrefix = root.endsWith("/") ? root : `${root}/`;
  if (!norm.startsWith(rootPrefix) && norm !== root) return false;
  const suffix = norm.startsWith(rootPrefix) ? norm.slice(rootPrefix.length) : "";
  return relPaths.some((rel) => rel === suffix);
}
