import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfigFromFile } from "vite";
import type { Plugin, UserConfig } from "vite";
import { resolveServePort } from "../shared/servePort";
import {
  REPORT_URL_PATH,
} from "../shared/paths";
import { resolveReportFilePath } from "../shared/reportPath";
import {
  collectScanModuleRelPaths,
  embedGlobKeyFromRelPath,
} from "./collectScanModules";
import {
  importerUnderScanRoot,
  INERTIA_SHIM_IDS,
  ZIGGY_SHIM_ID,
  type FlatAlias,
} from "./consumerAlias";
import { loadConsumerAliases } from "./loadConsumerAliases";
import {
  isWayfinderActionsImport,
  isWayfinderRoutesImport,
  resolveExistingModule,
  resolveWayfinderShim,
} from "./resolveWayfinderImport";

export const VIRTUAL_PLAYGROUND_MODULES_ID = "virtual:dslinter/playground-modules";
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_PLAYGROUND_MODULES_ID}`;

const pluginDir = dirname(fileURLToPath(import.meta.url));
const inertiaShimPath = resolve(pluginDir, "shims/inertia-react.tsx");
const ziggyShimPath = resolve(pluginDir, "shims/ziggy-js.ts");
const wayfinderRoutesShimPath = resolve(pluginDir, "shims/wayfinder-routes.ts");
const wayfinderActionsShimPath = resolve(pluginDir, "shims/wayfinder-actions.ts");

export type DslinterVitePluginOptions = {
  /** Scan root (repo root passed to `npx dslinter`). Defaults to `DSLINTER_SCAN_ROOT` or `process.cwd()`. */
  scanRoot?: string;
  /** Host Vite project root for `@/` aliases (Laravel/Inertia). */
  consumerViteRoot?: string;
  /** Scanner HTTP port for report + SSE proxy in `serve` mode. */
  servePort?: number;
};

function generatePlaygroundModulesSource(
  scanRoot: string,
  relPaths: string[],
): string {
  const root = resolve(scanRoot);
  const lines: string[] = [
    "// Generated by dslinter/vite — do not edit",
  ];

  for (let i = 0; i < relPaths.length; i++) {
    const rel = relPaths[i]!;
    const abs = resolve(root, rel).replace(/\\/g, "/");
    lines.push(`import * as __dslinter_m${i} from ${JSON.stringify(abs)};`);
  }

  lines.push("export const scanPlaygroundModules = {");
  for (let i = 0; i < relPaths.length; i++) {
    const key = embedGlobKeyFromRelPath(relPaths[i]!);
    lines.push(`  ${JSON.stringify(key)}: __dslinter_m${i},`);
  }
  lines.push("};");

  return lines.join("\n");
}

/**
 * Vite plugin: virtual playground module map, scanner proxy, react dedupe, fs.allow for scan root.
 *
 * @example
 * ```ts
 * import dslinter from "dslinter/vite";
 * export default defineConfig({ plugins: [dslinter()] });
 * ```
 */
export default function dslinter(
  options: DslinterVitePluginOptions = {},
): Plugin {
  const scanRoot = resolve(
    options.scanRoot ??
      process.env.DSLINTER_SCAN_ROOT ??
      process.cwd(),
  );
  const consumerViteRoot = resolve(
    options.consumerViteRoot ??
      process.env.DSLINTER_CONSUMER_VITE_ROOT ??
      "",
  );
  const servePort = options.servePort ?? resolveServePort();
  const consumerRoot =
    consumerViteRoot && existsSync(consumerViteRoot) ? consumerViteRoot : null;
  /** Populated synchronously so resolveId works before async configResolved. */
  let relPaths = collectScanModuleRelPaths(scanRoot);
  let consumerAliases: FlatAlias[] = consumerRoot
    ? loadConsumerAliases(consumerRoot, undefined)
    : [];

  return {
    name: "dslinter",
    enforce: "pre",
    /** Run before vite:alias so consumer @/ imports are not rewritten to embed src. */
    order: "pre",

    config(config, { mode }): UserConfig {
      const proxy =
        mode === "serve"
          ? {
              [REPORT_URL_PATH]: {
                target: `http://127.0.0.1:${servePort}`,
                changeOrigin: true,
              },
              "/events": {
                target: `http://127.0.0.1:${servePort}`,
                changeOrigin: true,
              },
            }
          : undefined;

      const allowRoots = [scanRoot];
      if (consumerViteRoot && existsSync(consumerViteRoot)) {
        allowRoots.push(consumerViteRoot);
      }
      const existingAllow = config.server?.fs?.allow;
      const fsAllow = Array.isArray(existingAllow)
        ? [...existingAllow, ...allowRoots]
        : allowRoots;

      return {
        resolve: {
          dedupe: ["react", "react-dom"],
        },
        optimizeDeps: {
          exclude: ["dslinter"],
        },
        server: {
          fs: {
            allow: fsAllow,
          },
          proxy,
        },
      };
    },

    async configResolved(config) {
      relPaths = collectScanModuleRelPaths(scanRoot);
      if (!consumerRoot) {
        consumerAliases = [];
        return;
      }
      try {
        const loaded = await loadConfigFromFile(
          { command: config.command, mode: config.mode },
          undefined,
          consumerRoot,
        );
        consumerAliases = loadConsumerAliases(
          consumerRoot,
          loaded?.config?.resolve?.alias,
        );
      } catch {
        consumerAliases = loadConsumerAliases(consumerRoot, undefined);
      }
    },

    resolveId(id, importer) {
      if (id === VIRTUAL_PLAYGROUND_MODULES_ID) {
        return RESOLVED_VIRTUAL_ID;
      }

      if (!importer || !importerUnderScanRoot(importer, scanRoot)) {
        return null;
      }

      if (INERTIA_SHIM_IDS.has(id) || id.startsWith("@inertiajs/react/")) {
        return inertiaShimPath;
      }
      if (id === ZIGGY_SHIM_ID || id === "ziggy") {
        return ziggyShimPath;
      }

      if (
        isWayfinderRoutesImport(id) ||
        isWayfinderActionsImport(id)
      ) {
        const onDisk = resolveExistingModule(id, consumerAliases);
        if (onDisk) return onDisk;
        const shim = resolveWayfinderShim(
          id,
          wayfinderRoutesShimPath,
          wayfinderActionsShimPath,
        );
        if (shim) return shim;
      }

      if (consumerAliases.length > 0) {
        const onDisk = resolveExistingModule(id, consumerAliases);
        if (onDisk) return onDisk;
      }

      return null;
    },

    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return;
      return generatePlaygroundModulesSource(scanRoot, relPaths);
    },

    configureServer(server) {
      const reportFile = resolveReportFilePath(scanRoot);

      server.middlewares.use((req, res, next) => {
        const path = req.url?.split("?")[0];
        if (path !== REPORT_URL_PATH) {
          next();
          return;
        }
        if (!existsSync(reportFile)) {
          next();
          return;
        }
        try {
          const stat = statSync(reportFile);
          const etag = `"${stat.mtimeMs}"`;
          res.setHeader("Content-Type", "application/json; charset=utf-8");
          res.setHeader("Cache-Control", "no-store");
          res.setHeader("ETag", etag);
          if (req.method === "HEAD") {
            res.statusCode = 200;
            res.end();
            return;
          }
          if (req.method === "GET") {
            res.end(readFileSync(reportFile));
            return;
          }
        } catch {
          // fall through to proxy / 404
        }
        next();
      });

      const refresh = () => {
        relPaths = collectScanModuleRelPaths(scanRoot);
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
        if (mod) server.moduleGraph.invalidateModule(mod);
      };
      server.watcher.add(scanRoot);
      server.watcher.on("add", refresh);
      server.watcher.on("unlink", refresh);
    },
  };
}

export { collectScanModuleRelPaths, embedGlobKeyFromRelPath };
