import { resolve } from "node:path";
import type { Plugin, UserConfig } from "vite";
import {
  collectScanModuleRelPaths,
  embedGlobKeyFromRelPath,
} from "./collectScanModules";

export const VIRTUAL_PLAYGROUND_MODULES_ID = "virtual:dslinter/playground-modules";
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_PLAYGROUND_MODULES_ID}`;

export type DslinterVitePluginOptions = {
  /** Scan root (repo root passed to `npx dslinter`). Defaults to `DSLINT_SCAN_ROOT` or `process.cwd()`. */
  scanRoot?: string;
  /** Scanner HTTP port for report + SSE proxy in `serve` mode. */
  servePort?: number;
};

function defaultServePort(): number {
  const fromEnv = process.env.DSLINT_SERVE_PORT?.trim();
  if (fromEnv) {
    const n = Number.parseInt(fromEnv, 10);
    if (Number.isFinite(n) && n > 0 && n <= 65535) return n;
  }
  return 7878;
}

function generatePlaygroundModulesSource(
  scanRoot: string,
  relPaths: string[],
): string {
  const root = resolve(scanRoot);
  const lines: string[] = [
    "// Generated by dslinter/vite — do not edit",
  ];

  for (let i = 0; i < relPaths.length; i++) {
    const rel = relPaths[i]!;
    const abs = resolve(root, rel).replace(/\\/g, "/");
    lines.push(`import * as __dslinter_m${i} from ${JSON.stringify(abs)};`);
  }

  lines.push("export const scanPlaygroundModules = {");
  for (let i = 0; i < relPaths.length; i++) {
    const key = embedGlobKeyFromRelPath(relPaths[i]!);
    lines.push(`  ${JSON.stringify(key)}: __dslinter_m${i},`);
  }
  lines.push("};");

  return lines.join("\n");
}

/**
 * Vite plugin: virtual playground module map, scanner proxy, react dedupe, fs.allow for scan root.
 *
 * @example
 * ```ts
 * import dslinter from "dslinter/vite";
 * export default defineConfig({ plugins: [dslinter()] });
 * ```
 */
export default function dslinter(
  options: DslinterVitePluginOptions = {},
): Plugin {
  const scanRoot = resolve(
    options.scanRoot ??
      process.env.DSLINT_SCAN_ROOT ??
      process.cwd(),
  );
  const servePort = options.servePort ?? defaultServePort();
  let relPaths: string[] = [];

  return {
    name: "dslinter",
    enforce: "pre",

    config(config, { mode }): UserConfig {
      const proxy =
        mode === "serve"
          ? {
              "/dslint-report.json": {
                target: `http://127.0.0.1:${servePort}`,
                changeOrigin: true,
              },
              "/events": {
                target: `http://127.0.0.1:${servePort}`,
                changeOrigin: true,
              },
            }
          : undefined;

      const existingAllow = config.server?.fs?.allow;
      const fsAllow = Array.isArray(existingAllow)
        ? [...existingAllow, scanRoot]
        : [scanRoot];

      return {
        resolve: {
          dedupe: ["react", "react-dom"],
        },
        optimizeDeps: {
          exclude: ["dslinter"],
        },
        server: {
          fs: {
            allow: fsAllow,
          },
          proxy,
        },
      };
    },

    configResolved() {
      relPaths = collectScanModuleRelPaths(scanRoot);
    },

    resolveId(id) {
      if (id === VIRTUAL_PLAYGROUND_MODULES_ID) {
        return RESOLVED_VIRTUAL_ID;
      }
    },

    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return;
      return generatePlaygroundModulesSource(scanRoot, relPaths);
    },

    configureServer(server) {
      const refresh = () => {
        relPaths = collectScanModuleRelPaths(scanRoot);
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
        if (mod) server.moduleGraph.invalidateModule(mod);
      };
      server.watcher.add(scanRoot);
      server.watcher.on("add", refresh);
      server.watcher.on("unlink", refresh);
    },
  };
}

export { collectScanModuleRelPaths, embedGlobKeyFromRelPath };
