packages:
  - "demo/inertia"
  - "demo/react"
  - "packages/dashboard"

publicHoistPattern:
  - "@inertiajs/core"
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  workerd: true
