/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function runCli(args: Array<string>): number

/** Scan a workspace and return the full report as a JSON string (for MCP / programmatic use). */
export declare function scanWorkspaceJson(root: string, parallel?: boolean | undefined | null): string
